# Generated by Django 3.2.9 on 2021-11-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20211118_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_area',
            field=models.CharField(max_length=200, null=True, verbose_name='房屋面积'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_location',
            field=models.CharField(max_length=200, null=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(max_length=200, null=True, verbose_name='房屋名称'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_price',
            field=models.CharField(max_length=200, null=True, verbose_name='租价'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(max_length=200, null=True, verbose_name='房型'),
        ),
    ]
